-- ================================================================
-- PIRO — Insert Products
-- در Supabase Dashboard → SQL Editor اجرا کنید
-- ================================================================

INSERT INTO public.products (id, var_group, var_order, variant_label, category, sub, name_fa, name_en, price, image, image2, badge, is_active) VALUES
('tehran1','tehran',1,'تک‌نفره','living','sofa','کاناپه تهران','Tehran Sofa','۷۸,۰۰۰,۰۰۰','tehran1.jpg','tehran1-d.jpg','پرفروش',true),
('tehran25','tehran',2,'دونفره','living','sofa','کاناپه تهران','Tehran Sofa','۱۰۵,۰۰۰,۰۰۰','tehran25.jpg','tehran25-d.jpg',null,true),
('tehran35','tehran',3,'سه‌نفره','living','sofa','کاناپه تهران','Tehran Sofa','۱۳۸,۰۵۰,۰۰۰','tehran35.jpg','tehran35-d.jpg',null,true),
('tehranl','tehran',4,'ال‌شکل','living','sofa','کاناپه تهران','Tehran Sofa','۱۴۵,۰۰۰,۰۰۰','tehranl.jpg','tehranl-d.jpg',null,true),
('tehrancl','tehran',5,'شزلون','living','sofa','کاناپه تهران','Tehran Sofa','۱۱۵,۰۰۰,۰۰۰','tehrancl.jpg','tehrancl-d.jpg',null,true),
('palma1','palma',1,'تک‌نفره','living','sofa','کاناپه پالما','Palma Sofa','۶۵,۴۵۰,۰۰۰','palma1.jpg','palma1-d.jpg',null,true),
('palma2','palma',2,'دونفره','living','sofa','کاناپه پالما','Palma Sofa','۹۲,۰۰۰,۰۰۰','palma2.jpg','palma2-d.jpg',null,true),
('palma3','palma',3,'سه‌نفره','living','sofa','کاناپه پالما','Palma Sofa','۱۱۲,۷۵۰,۰۰۰','palma3.jpg','palma3-d.jpg',null,true),
('palmal','palma',4,'ال‌شکل','living','sofa','کاناپه پالما','Palma Sofa','۱۳۵,۰۰۰,۰۰۰','palmal.jpg','palmal-d.jpg',null,true),
('palmacl','palma',5,'شزلون','living','sofa','کاناپه پالما','Palma Sofa','۱۰۵,۰۰۰,۰۰۰','palmacl.jpg','palmacl-d.jpg',null,true),
('hermosa1','hermosa',1,'تک‌نفره','living','sofa','کاناپه هرموسا','Hermosa Sofa','۸۵,۰۰۰,۰۰۰','hermosa1.jpg','hermosa1-d.jpg','جدید',true),
('hermosa2','hermosa',2,'دونفره','living','sofa','کاناپه هرموسا','Hermosa Sofa','۱۲۹,۲۵۰,۰۰۰','hermosa2.jpg','hermosa2-d.jpg',null,true),
('hermosa3','hermosa',3,'سه‌نفره','living','sofa','کاناپه هرموسا','Hermosa Sofa','۱۶۵,۰۰۰,۰۰۰','hermosa3.jpg','hermosa3-d.jpg',null,true),
('muge1','muge',1,'تک‌نفره','living','sofa','کاناپه موژه','Muge Sofa','۸۶,۳۵۰,۰۰۰','muge1.jpg','muge1-live.jpg',null,true),
('muge2','muge',2,'دونفره','living','sofa','کاناپه موژه','Muge Sofa','۱۳۸,۰۵۰,۰۰۰','muge2.jpg','muge2-live.jpg',null,true),
('gordo1','gordo',1,'تک‌نفره','living','sofa','کاناپه گوردو','Gordo Sofa','۶۶,۰۰۰,۰۰۰','gordo1.jpg','gordo1-d.jpg',null,true),
('gordo2','gordo',2,'دونفره','living','sofa','کاناپه گوردو','Gordo Sofa','۸۸,۰۰۰,۰۰۰','gordo2.jpg','gordo2-d.jpg',null,true),
('gordocl','gordo',3,'+شزلون','living','sofa','کاناپه گوردو','Gordo Sofa','۱۱۵,۰۰۰,۰۰۰','gordocl.jpg','gordocl-d.jpg',null,true),
('shito2','shito',1,'دونفره','living','sofa','کاناپه شیتو','Shito Sofa','۸۸,۰۰۰,۰۰۰','shito2.jpg','shito2-d.jpg',null,true),
('shito3','shito',2,'سه‌نفره','living','sofa','کاناپه شیتو','Shito Sofa','۱۱۵,۰۰۰,۰۰۰','shito3.jpg','shito3-d.jpg',null,true),
('shitol','shito',3,'ال‌شکل','living','sofa','کاناپه شیتو','Shito Sofa','۱۳۵,۰۰۰,۰۰۰','shitol.jpg','shitol-d.jpg',null,true),
('shitocl','shito',4,'شزلون','living','sofa','کاناپه شیتو','Shito Sofa','۱۰۵,۰۰۰,۰۰۰','shitocl.jpg','shitocl-d.jpg',null,true),
('diba2','diba',1,'دونفره','living','sofa','کاناپه دیبا','Diba Sofa','۹۸,۴۵۰,۰۰۰','diba2.jpg','diba2-d.jpg',null,true),
('diba3','diba',2,'سه‌نفره','living','sofa','کاناپه دیبا','Diba Sofa','۱۲۵,۰۰۰,۰۰۰','diba3.jpg','diba3-d.jpg',null,true),
('henka',null,0,'تک‌نفره','living','sofa','کاناپه هنکا','Henka Sofa','۸۶,۳۵۰,۰۰۰','henka.jpg','henka-d.jpg',null,true),
('hamdam',null,0,null,'living','bench','نیمکت همدم','Hamdam Loveseat','۵۵,۰۰۰,۰۰۰','hamdam.jpg','hamdam-d.jpg',null,true),
('lam',null,0,null,'living','lounge','مبل راحتی لَم','Lam Lounge Chair','۶۵,۴۵۰,۰۰۰','lam.jpg','lam-d.jpg',null,true),
('blando',null,0,null,'living','lounge','مبل راحتی بلاندو','Blando Lounge Chair','۶۱,۰۵۰,۰۰۰','blando.jpg','blando-d.jpg',null,true),
('zen',null,0,null,'living','chair','صندلی زِن','Zen Chair','۱۹,۲۵۰,۰۰۰','zen.jpg','zen-d.jpg','پرفروش',true),
('hyrcani',null,0,null,'living','chair','صندلی هیرکانی','Hyrcani Chair','۲۲,۰۰۰,۰۰۰','hyrcani.jpg','hyrcani-d.jpg',null,true),
('kara',null,0,null,'living','chair','صندلی کارا','Kara Chair','۲۳,۰۰۰,۰۰۰','kara.jpg','kara-d.jpg',null,true),
('lean',null,0,null,'living','chair','صندلی لین','Lean Chair','۱۶,۵۰۰,۰۰۰','lean.jpg','lean-d.jpg',null,true),
('chairb',null,0,null,'living','chair','صندلی بی','Chair B','۲۵,۰۰۰,۰۰۰','chairb.jpg','chairb-d.jpg',null,true),
('alef',null,0,null,'living','barstool','استول الف','Alef Barstool','۱۴,۵۰۰,۰۰۰','alef.jpg','alef-d.jpg',null,true),
('leanbar',null,0,null,'living','barstool','استول لین','Lean Barstool','۱۲,۵۰۰,۰۰۰','leanbar.jpg','leanbar-d.jpg',null,true),
('lat120','lat',1,'۱۲۰cm','living','bench','نیمکت لَت','Lat Bench','۴۵,۰۰۰,۰۰۰','lat120.jpg','lat120-d.jpg',null,true),
('lat150','lat',2,'۱۵۰cm','living','bench','نیمکت لَت','Lat Bench','۵۲,۸۰۰,۰۰۰','lat150.jpg','lat150-d.jpg',null,true),
('lat200','lat',3,'۲۰۰cm','living','bench','نیمکت لَت','Lat Bench','۶۵,۰۰۰,۰۰۰','lat200.jpg','lat200-d.jpg',null,true),
('mogensen','mogensen',1,'کوتاه','living','bench','نیمکت موگنسن','Mogensen Bench','۳۵,۰۰۰,۰۰۰','mogensen.jpg','mogensen-d.jpg',null,true),
('mogensen2','mogensen',2,'بلند','living','bench','نیمکت موگنسن','Mogensen Bench','۳۵,۰۰۰,۰۰۰','mogensen2.jpg','mogensen2-d.jpg',null,true),
('nosha90','nosha',1,'۹۰×۲۰۰','bedroom','bed','تخت‌خواب نوشا','Nosha Bed','۷۱,۵۰۰,۰۰۰','nosha90.jpg','nosha90-d.jpg',null,true),
('nosha160','nosha',2,'۱۶۰×۲۰۰','bedroom','bed','تخت‌خواب نوشا','Nosha Bed','۷۸,۰۰۰,۰۰۰','nosha160.jpg','nosha160-d.jpg',null,true),
('linda160',null,0,'۱۶۰×۲۰۰','bedroom','bed','تخت‌خواب لیندا','Linda Bed','۸۵,۰۰۰,۰۰۰','linda160.jpg','linda160-d.jpg',null,true),
('neda90','neda',1,'۹۰×۲۰۰','bedroom','bed','تخت‌خواب ندا','Neda Bed','۷۵,۰۰۰,۰۰۰','neda90.jpg','neda90-d.jpg','جدید',true),
('neda160','neda',2,'۱۶۰×۲۰۰','bedroom','bed','تخت‌خواب ندا','Neda Bed','۸۸,۰۰۰,۰۰۰','neda160.jpg','neda160-d.jpg','جدید',true),
('elara160',null,0,'۱۶۰×۲۰۰','bedroom','bed','تخت‌خواب الارا','Elara Bed','۱۰۴,۵۰۰,۰۰۰','elara160-d.jpg','elara160-d.jpg',null,true),
('mono',null,0,null,'bedroom','nightstand','پاتختی مونو','Mono Nightstand','۱۲,۰۰۰,۰۰۰','mono.jpg','mono-d.jpg',null,true),
('nightmood',null,0,null,'bedroom','nightstand','پاتختی مود','Mood Nightstand','۱۸,۰۰۰,۰۰۰','nightmood.jpg','nightmood-d.jpg',null,true),
('dresser',null,0,null,'bedroom','dresser','دراور مود','Mood Dresser','۴۵,۰۰۰,۰۰۰','dresser.jpg','dresser-d.jpg',null,true),
('dresser2',null,0,null,'bedroom','dresser','دراور مود لارج','Mood Dresser Large','۶۵,۰۰۰,۰۰۰','dresser2.jpg','dresser2-d.jpg',null,true),
('tana',null,0,null,'bedroom','hanger','رخت‌آویز تانا','Tana Clothes Hanger','۲۸,۰۰۰,۰۰۰','tana.jpg','tana-d.jpg',null,true),
('arasbaran6','arasbaran',1,'۶ نفره','tables','dining','میز ارسباران','Arasbaran Dining Table','۱۱۲,۰۰۰,۰۰۰','arasbaran6.jpg','arasbaran6-d.jpg','جدید',true),
('arasbaran8','arasbaran',2,'۸ نفره','tables','dining','میز ارسباران','Arasbaran Dining Table','۱۳۵,۰۰۰,۰۰۰','arasbaran8.jpg','arasbaran8-d.jpg',null,true),
('cerca4','cerca',1,'۴ نفره','tables','dining','میز سِرکا','Cerca Dining Table','۷۱,۵۰۰,۰۰۰','cerca4.jpg','cerca4-d.jpg',null,true),
('cerca8','cerca',2,'۸ نفره','tables','dining','میز سِرکا','Cerca Dining Table','۹۵,۰۰۰,۰۰۰','cerca8.jpg','cerca8-d.jpg',null,true),
('kaya4',null,0,'۴ نفره','tables','dining','میز کایا','Kaya Dining Table','۷۵,۹۰۰,۰۰۰','kaya4-d.jpg','kaya4-d.jpg',null,true),
('diningmood',null,0,null,'tables','dining','میز ناهارخوری مود','Mood Dining Table','۸۸,۰۰۰,۰۰۰','diningmood.jpg','diningmood-d.jpg',null,true),
('ox',null,0,null,'tables','dining','میز ناهارخوری OX','OX Dining Table','۹۵,۰۰۰,۰۰۰','ox.jpg','ox-d.jpg',null,true),
('talk',null,0,null,'tables','dining','میز ناهارخوری تاک','Talk Dining Table','۸۵,۰۰۰,۰۰۰','talk-d.jpg','talk-live.jpg',null,true),
('pianura',null,0,null,'tables','dining','میز پیانورا','Pianura Dining Table','۷۸,۰۰۰,۰۰۰','pianura.jpg','pianura-d.jpg',null,true),
('diningsimple',null,0,null,'tables','dining','میز ناهارخوری سیمپل','Simple Dining Table','۶۵,۰۰۰,۰۰۰','diningsimple.jpg','diningsimple-d.jpg',null,true),
('emi',null,0,null,'tables','coffee','میز جلو‌مبلی امی','EMI Coffee Table','۷۱,۵۰۰,۰۰۰','emi.jpg','emi-d.jpg',null,true),
('en',null,0,null,'tables','coffee','میز جلو‌مبلی EN','EN Coffee Table','۲۸,۰۰۰,۰۰۰','en.jpg','en-d.jpg',null,true),
('kazoko',null,0,null,'tables','coffee','میز جلو‌مبلی کازوکو','Kazoko Coffee Table','۳۸,۰۰۰,۰۰۰','kazoko.jpg','kazoko-d.jpg',null,true),
('sencilla',null,0,null,'tables','coffee','میز جلو‌مبلی سنسیلا','Sencilla Coffee Table','۲۵,۰۰۰,۰۰۰','sencilla.jpg','sencilla-d.jpg',null,true),
('shonin',null,0,null,'tables','coffee','میز جلو‌مبلی شونین','Shonin Coffee Table','۳۲,۰۰۰,۰۰۰','shonin.jpg','shonin-d.jpg',null,true),
('coffeesimple',null,0,null,'tables','coffee','میز جلو‌مبلی سیمپل','Simple Coffee Table','۲۸,۰۰۰,۰۰۰','coffeesimple.jpg','coffeesimple-d.jpg',null,true),
('sideen',null,0,null,'tables','sidetable','میز عسلی EN','EN Side Table','۴۹,۵۰۰,۰۰۰','sideen.jpg','sideen-d.jpg',null,true),
('sidemore',null,0,null,'tables','sidetable','میز عسلی مور','More Side Table','۲۲,۰۰۰,۰۰۰','sidemore.jpg','sidemore-d.jpg',null,true),
('nik',null,0,null,'tables','sidetable','میز عسلی نیک','Nik Side Table','۱۵,۰۰۰,۰۰۰','nik.jpg','nik-d.jpg',null,true),
('sidesencilla',null,0,null,'tables','sidetable','میز عسلی سنسیلا','Sencilla Side Table','۱۸,۰۰۰,۰۰۰','sidesencilla.jpg','sidesencilla-d.jpg',null,true),
('shonins',null,0,null,'tables','sidetable','میز عسلی شونین','Shonin Side Table','۱۸,۰۰۰,۰۰۰','shonins.jpg','shonins-d.jpg',null,true),
('alto',null,0,null,'tables','bartable','میز بار آلتو','Alto Bar Table','۴۹,۵۰۰,۰۰۰','alto.jpg','alto-d.jpg',null,true),
('etude',null,0,null,'tables','desk','میز تحریر اِتود','Etude Writing Desk','۹۵,۱۵۰,۰۰۰','etude-d.jpg','etude-d.jpg','جدید',true),
('rain',null,0,null,'tables','desk','میز تحریر رَین','Rain Writing Desk','۷۸,۰۰۰,۰۰۰','rain-d.jpg','rain-live.jpg',null,true),
('sketch',null,0,null,'tables','desk','میز تحریر اسکچ','Sketch Writing Desk','۵۵,۰۰۰,۰۰۰','sketch-d.jpg','sketch-live.jpg',null,true),
('sense',null,0,null,'tables','vanity','میز آرایش سنس','Sense Vanity Table','۴۵,۰۰۰,۰۰۰','sense.jpg','sense-d.jpg',null,true),
('sideboard',null,0,null,'console','sideboard','سایدبورد مود کوچک','Mood Sideboard Small','۶۲,۰۰۰,۰۰۰','sideboard.jpg','sideboard-d.jpg',null,true),
('sideboard2',null,0,null,'console','sideboard','سایدبورد مود بزرگ','Mood Sideboard Large','۸۸,۰۰۰,۰۰۰','sideboard2.jpg','sideboard2-d.jpg',null,true),
('console110','consolemood',1,'۱۱۰cm','console','consoleunit','کنسول مود','Mood Console','۳۵,۰۰۰,۰۰۰','console110.jpg','console110-d.jpg',null,true),
('console130','consolemood',2,'۱۳۰cm','console','consoleunit','کنسول مود','Mood Console','۴۵,۰۰۰,۰۰۰','console130.jpg','console130-d.jpg',null,true),
('largo',null,0,null,'console','tv','میز تلویزیون لارگو','Largo TV Console','۵۵,۰۰۰,۰۰۰','largo.jpg','largo-d.jpg',null,true),
('tvmood2',null,0,null,'console','tv','میز تلویزیون مود ۲','Mood TV Console 2','۴۲,۰۰۰,۰۰۰','tvmood2.jpg','tvmood2-live.jpg',null,true),
('tvmood3',null,0,null,'console','tv','میز تلویزیون مود ۳','Mood TV Console 3','۵۵,۰۰۰,۰۰۰','tvmood3.jpg','tvmood3-d.jpg',null,true),
('cabinet',null,0,null,'console','cabinet','کابینت مود','Mood Cabinet','۵۵,۰۰۰,۰۰۰','cabinet.jpg','cabinet-d.jpg',null,true),
('mirror',null,0,null,'console','mirror','آینه میرو','Miro Mirror','۱۵,۵۰۰,۰۰۰','mirror.jpg','mirror-d.jpg',null,true),
('piso',null,0,null,'console','shelf','شلف پیزو','Piso Shelf','۱۸,۰۰۰,۰۰۰','piso-d.jpg','piso-live.jpg',null,true),
('sheen2s',null,0,null,'console','shelf','شلف شین کوتاه ۲طبقه','Sheen Short 2S Shelf','۳۵,۰۰۰,۰۰۰','sheen2s.jpg','sheen2s-d.jpg',null,true),
('sheen3s',null,0,null,'console','shelf','شلف شین کوتاه ۳طبقه','Sheen Short 3S Shelf','۴۵,۰۰۰,۰۰۰','sheen3s.jpg','sheen3s-d.jpg',null,true),
('sheentall',null,0,null,'console','shelf','شلف شین بلند','Sheen Tall Shelf','۷۵,۳۵۰,۰۰۰','sheentall.jpg','sheentall-d.jpg',null,true),
('sheenw',null,0,null,'console','shelf','شلف شین عریض','Sheen Wide Shelf','۶۵,۰۰۰,۰۰۰','sheenw.jpg','sheenw-d.jpg',null,true),
('kido2','kido',1,'کوتاه','console','lamp','آباژور کیدو','Kido Floor Lamp','۱۶,۵۰۰,۰۰۰','kido2.jpg','kido2-d.jpg',null,true),
('kido','kido',2,'بلند','console','lamp','آباژور کیدو','Kido Floor Lamp','۱۶,۵۰۰,۰۰۰','kido.jpg','kido-d.jpg',null,true),
('rash',null,0,null,'console','lamp','آباژور رَش','Rash Floor Lamp','۱۸,۰۰۰,۰۰۰','rash.jpg','rash-d.jpg',null,true),
('freshboxl',null,0,null,'console','cabinet','باکس طبیعی بزرگ','Fresh Box Large','۱۲۶,۵۰۰,۰۰۰','freshboxl.jpg','freshboxl-d.jpg',null,true),
('freshboxs',null,0,null,'console','cabinet','باکس طبیعی کوچک','Fresh Box Small','۶۵,۰۰۰,۰۰۰','freshboxs.jpg','freshboxs-d.jpg',null,true)
ON CONFLICT (id) DO UPDATE SET
  var_group = EXCLUDED.var_group,
  var_order = EXCLUDED.var_order,
  variant_label = EXCLUDED.variant_label,
  name_fa = EXCLUDED.name_fa,
  name_en = EXCLUDED.name_en,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  image2 = EXCLUDED.image2,
  badge = EXCLUDED.badge,
  is_active = EXCLUDED.is_active;
